"""
Reducer node of the OmniBrain AI Intelligence Layer.
Consolidates multi-agent parallel responses, resolves output conflicts, deduplicates citations, aggregates confidence scores, and finalizes response state.
"""

from typing import Dict, Any, List
from agents.state import AgentState
from agents.prompts import REDUCER_PROMPT
from agents.llm import invoke_llm
from agents.logger import get_logger, log_agent_execution
from agents.utils import ExecutionTimer, sanitize_prompt_input

logger = get_logger("omnibrain.agents.reducer")


def reducer(state: AgentState) -> AgentState:
    """
    Reducer node:
    - Inspects state['agent_responses'] dictionary collected from parallel nodes.
    - If multiple agent outputs exist, calls Master Reducer LLM to consolidate into a coherent synthesis.
    - Aggregates confidence scores across executed specialist agents.
    - Deduplicates citations by (page, source_type, snippet).
    - Appends final reduction telemetry trace.

    Args:
        state (AgentState): Current execution state.

    Returns:
        AgentState: Finalized execution state.
    """
    with ExecutionTimer() as timer:
        question = sanitize_prompt_input(state.get("question", ""))
        logger.info("Reducer node consolidating agent responses.")

        try:
            agent_responses: Dict[str, str] = state.get("agent_responses") or {}

            # Handle case where single response was assigned directly to state['response']
            if not agent_responses and state.get("response"):
                selected_primary = state.get("selected_agent", "specialist")
                agent_responses[selected_primary] = state["response"]

            if not agent_responses:
                logger.warning("No responses generated by specialist agents. Using standard fallback answer.")
                state["response"] = "I don't have enough information to answer this question."
            elif len(agent_responses) == 1:
                # Single agent execution path
                single_agent_name, single_response = next(iter(agent_responses.items()))
                state["response"] = single_response
                logger.info("Single agent response retained from '%s'.", single_agent_name)
            else:
                # Multi-agent synthesis path
                formatted_outputs = "\n\n".join(
                    f"--- AGENT [{name.upper()}] OUTPUT ---\n{resp}" 
                    for name, resp in agent_responses.items()
                )
                reducer_system_prompt = REDUCER_PROMPT.format(
                    specialist_outputs=formatted_outputs,
                    question=question
                )
                logger.info("Synthesizing multi-agent outputs from agents: %s", list(agent_responses.keys()))
                consolidated_answer = invoke_llm(
                    prompt=f"Consolidate responses for question: {question}",
                    system_prompt=reducer_system_prompt
                )
                state["response"] = consolidated_answer

            # Aggregate Confidence Scores
            confidence_map = state.get("confidence_scores") or {}
            scores = [v for k, v in confidence_map.items() if k != "supervisor" and isinstance(v, (int, float))]
            avg_confidence = round(sum(scores) / len(scores), 2) if scores else 0.85
            confidence_map["reducer"] = avg_confidence
            state["confidence_scores"] = confidence_map

            metrics_map = state.get("execution_metrics") or {}
            metrics_map["reducer_ms"] = round(timer.elapsed_ms, 2)
            state["execution_metrics"] = metrics_map

            # Ensure collections exist
            state["citations"] = state.get("citations") or []
            state["retrieved_docs"] = state.get("retrieved_docs") or []
            state["retrieved_images"] = state.get("retrieved_images") or []

            # Deduplicate citations
            unique_citations: List[Dict[str, Any]] = []
            seen_keys = set()

            for cit in state["citations"]:
                if isinstance(cit, dict):
                    page = cit.get("page", 1)
                    stype = cit.get("source_type", "unknown")
                    snip = str(cit.get("snippet", ""))[:100]
                    key = (page, stype, snip)

                    if key not in seen_keys:
                        seen_keys.add(key)
                        unique_citations.append(cit)

            state["citations"] = unique_citations
            state["agent_trace"] = ["Reducer: Consolidated final response and deduplicated citations"]

            log_agent_execution(
                logger=logger,
                agent_name="reducer",
                query=question,
                execution_time_ms=timer.elapsed_ms,
                status="SUCCESS",
                extra_metadata={"unique_citations": len(unique_citations), "final_confidence": avg_confidence}
            )

        except Exception as exc:
            logger.exception("Error in Reducer node: %s", exc)
            state["agent_trace"] = [f"Reducer error: {str(exc)}"]
            if not state.get("response"):
                state["response"] = "An error occurred while consolidating multi-agent outputs."

            log_agent_execution(
                logger=logger,
                agent_name="reducer",
                query=question,
                execution_time_ms=timer.elapsed_ms,
                status="FAILED",
                extra_metadata={"error": str(exc)}
            )

    return state
