"""
Reducer node of the OmniBrain AI Intelligence Layer.
Consolidates multi-agent parallel responses, resolves output conflicts, deduplicates citations, and finalizes response state.
"""

from typing import Dict, Any, List
from agents.state import AgentState
from agents.prompts import REDUCER_PROMPT
from agents.llm import invoke_llm
from agents.logger import get_logger, log_agent_execution
from agents.utils import ExecutionTimer, sanitize_prompt_input

logger = get_logger("omnibrain.agents.reducer")


def reducer(state: AgentState) -> Dict[str, Any]:
    """
    Reducer node:
    - Inspects state['agent_responses'] dictionary collected from parallel nodes.
    - If multiple agent outputs exist, calls Master Reducer LLM to consolidate into a coherent synthesis.
    - If single response exists, uses it directly.
    - Deduplicates citations by (page, source_type, snippet).
    - Appends final reduction telemetry trace.

    Args:
        state (AgentState): Current execution state.

    Returns:
        Dict[str, Any]: Partial state update with synthesized response and deduplicated citations.
    """
    with ExecutionTimer() as timer:
        question = sanitize_prompt_input(state.get("question", ""))
        logger.info("Reducer node consolidating agent responses.")

        try:
            agent_responses: Dict[str, str] = state.get("agent_responses") or {}

            # Handle case where single response was assigned directly to state['response']
            if not agent_responses and state.get("response"):
                selected_primary = state.get("selected_agent", "specialist")
                agent_responses[selected_primary] = state["response"]

            final_response = ""
            if not agent_responses:
                logger.warning("No responses generated by specialist agents. Using standard fallback answer.")
                final_response = "I don't have enough information to answer this question."
            elif len(agent_responses) == 1:
                # Single agent execution path
                single_agent_name, single_response = next(iter(agent_responses.items()))
                final_response = single_response
                logger.info("Single agent response retained from '%s'.", single_agent_name)
            else:
                # Multi-agent synthesis path
                formatted_outputs = "\n\n".join(
                    f"--- AGENT [{name.upper()}] OUTPUT ---\n{resp}" 
                    for name, resp in agent_responses.items()
                )
                reducer_system_prompt = REDUCER_PROMPT.format(
                    specialist_outputs=formatted_outputs,
                    question=question
                )
                logger.info("Synthesizing multi-agent outputs from agents: %s", list(agent_responses.keys()))
                final_response = invoke_llm(
                    prompt=f"Consolidate responses for question: {question}",
                    system_prompt=reducer_system_prompt
                )

            # Deduplicate citations
            raw_citations = state.get("citations") or []
            unique_citations: List[Dict[str, Any]] = []
            seen_keys = set()

            for cit in raw_citations:
                if isinstance(cit, dict):
                    page = cit.get("page", 1)
                    stype = cit.get("source_type", "unknown")
                    snip = cit.get("snippet", "")[:100]
                    key = (page, stype, snip)

                    if key not in seen_keys:
                        seen_keys.add(key)
                        unique_citations.append(cit)

            log_agent_execution(
                logger=logger,
                agent_name="reducer",
                query=question,
                execution_time_ms=timer.elapsed_ms,
                status="SUCCESS",
                extra_metadata={"unique_citations": len(unique_citations)}
            )

            return {
                "response": final_response,
                "citations": unique_citations,
                "agent_trace": ["Reducer: Consolidated final response and deduplicated citations"]
            }

        except Exception as exc:
            logger.exception("Error in Reducer node: %s", exc)
            log_agent_execution(
                logger=logger,
                agent_name="reducer",
                query=question,
                execution_time_ms=timer.elapsed_ms,
                status="FAILED",
                extra_metadata={"error": str(exc)}
            )

            fallback_resp = state.get("response") or "An error occurred while consolidating multi-agent outputs."
            return {
                "response": fallback_resp,
                "agent_trace": [f"Reducer error: {str(exc)}"]
            }
